/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bootstrap */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["resetDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock Person
         * @description Demo PIN check before switching person. Not authentication.
         */
        post: operations["unlockPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/rest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rest Plan */
        post: operations["createRestPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Plan */
        post: operations["confirmPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenes */
        get: operations["getScenes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{service_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Service */
        post: operations["stopService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device State */
        get: operations["getDeviceState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Event
         * @description Simulated environment event. There is no real sensor; results are labelled source=simulated.
         */
        post: operations["injectEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionResult */
        ActionResult: {
            /** Actionid */
            actionId: string;
            /**
             * Command
             * @enum {string}
             */
            command: "set_brightness" | "set_target_temperature" | "set_open_percent";
            /**
             * Device
             * @enum {string}
             */
            device: "light" | "ac" | "curtain";
            /**
             * Observedvalue
             * @description Value read back from the device after the write
             */
            observedValue: number | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "succeeded" | "rejected" | "failed" | "skipped";
            /** Reason */
            reason: string | null;
            /** Value */
            value: number;
        };
        /** ActivityRecord */
        ActivityRecord: {
            action: components["schemas"]["ActionResult"] | null;
            /** Activityid */
            activityId: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "plan_created" | "plan_fallback" | "event_received" | "event_ignored" | "service_adjusted" | "plan_confirmed" | "plan_confirm_repeated" | "plan_rejected" | "action_executed" | "action_rejected" | "service_stopped" | "demo_reset";
            /** Message */
            message: string;
            /** Personid */
            personId: string | null;
            /** Planid */
            planId: string | null;
            /** Serviceid */
            serviceId: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "user" | "rule_engine" | "experience_agent" | "executor" | "virtual_device" | "system" | "simulated_event" | "frontend_mock";
            /** Spaceid */
            spaceId: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ActivityResponse */
        ActivityResponse: {
            /** Items */
            items: components["schemas"]["ActivityRecord"][];
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            account: components["schemas"]["DemoAccount"];
            activeService: components["schemas"]["Service"] | null;
            /** Defaultspaceid */
            defaultSpaceId: string;
            deviceState: components["schemas"]["DeviceState"];
            /**
             * Mode
             * @constant
             */
            mode: "demo";
            /** Persons */
            persons: components["schemas"]["Person"][];
            planner: components["schemas"]["PlannerInfo"];
            /** Spaces */
            spaces: components["schemas"]["Space"][];
        };
        /** ConfirmPlanRequest */
        ConfirmPlanRequest: {
            context: components["schemas"]["RequestContext"];
            /** Planversion */
            planVersion: number;
        };
        /** ConfirmPlanResponse */
        ConfirmPlanResponse: {
            deviceState: components["schemas"]["DeviceState"];
            plan: components["schemas"]["Plan"];
            /**
             * Repeated
             * @description True when the plan was already executed; nothing was re-run
             */
            repeated: boolean;
            /** Results */
            results: components["schemas"]["ActionResult"][];
            service: components["schemas"]["Service"];
        };
        /** CreateRestPlanRequest */
        CreateRestPlanRequest: {
            context: components["schemas"]["RequestContext"];
            /**
             * Mode
             * @description null = server default
             */
            mode?: ("rule" | "model") | null;
            /** Utterance */
            utterance: string;
        };
        /**
         * DemoAccount
         * @description Demo identity only. This is NOT authentication.
         */
        DemoAccount: {
            /** Accountid */
            accountId: string;
            /** Displayname */
            displayName: string;
            /** Isdemo */
            isDemo: boolean;
        };
        /** DeviceAction */
        DeviceAction: {
            /** Actionid */
            actionId: string;
            /**
             * Command
             * @enum {string}
             */
            command: "set_brightness" | "set_target_temperature" | "set_open_percent";
            /**
             * Device
             * @enum {string}
             */
            device: "light" | "ac" | "curtain";
            /**
             * Label
             * @description Human readable description shown in the app
             */
            label: string;
            /** Value */
            value: number;
        };
        /** DeviceState */
        DeviceState: {
            /** Actargettempc */
            acTargetTempC: number;
            /** Curtainopenpercent */
            curtainOpenPercent: number;
            /** Lightbrightness */
            lightBrightness: number;
            /**
             * Source
             * @enum {string}
             */
            source: "virtual_device" | "frontend_mock";
            /** Spaceid */
            spaceId: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /**
             * Version
             * @description Increments on every successful device write
             */
            version: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "VALIDATION_ERROR" | "NOT_FOUND" | "FORBIDDEN_CONTEXT" | "PLAN_EXPIRED" | "PLAN_INVALIDATED" | "PLAN_VERSION_MISMATCH" | "SERVICE_ALREADY_ACTIVE" | "SERVICE_NOT_ACTIVE" | "PIN_INVALID" | "INTERNAL_ERROR";
            /** Details */
            details: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EventResult */
        EventResult: {
            deviceState: components["schemas"]["DeviceState"];
            /** Eventid */
            eventId: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "adjusted" | "ignored";
            /** @description The adjustment plan that was executed */
            plan: components["schemas"]["Plan"] | null;
            /**
             * Reason
             * @description Why the event was ignored, if it was
             */
            reason: string | null;
            /** Results */
            results: components["schemas"]["ActionResult"][];
            service: components["schemas"]["Service"] | null;
            /**
             * Source
             * @constant
             */
            source: "simulated";
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InjectEventRequest
         * @description Simulated environment event (demo only; there is no real sensor).
         */
        InjectEventRequest: {
            context: components["schemas"]["RequestContext"];
            /** Roomtempc */
            roomTempC: number;
            /**
             * Type
             * @constant
             */
            type: "room_temperature_changed";
        };
        /** Person */
        Person: {
            /**
             * Avatarcolor
             * @description Display color for the avatar
             */
            avatarColor: string;
            /** Description */
            description: string;
            /**
             * Haspin
             * @description A demo PIN guards switching to this person (the PIN itself is never sent)
             */
            hasPin: boolean;
            /**
             * Isguest
             * @description Guest / shared-space context: space defaults, no personal profile
             */
            isGuest: boolean;
            /** Name */
            name: string;
            /** Personid */
            personId: string;
            restPreference: components["schemas"]["RestPreference"];
        };
        /** Plan */
        Plan: {
            /** Actions */
            actions: components["schemas"]["DeviceAction"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            generation: components["schemas"]["PlanGeneration"];
            /** Notes */
            notes: string[];
            /** Personid */
            personId: string;
            /** Planid */
            planId: string;
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "rest" | "rest_adjustment";
            /**
             * Source
             * @enum {string}
             */
            source: "rule" | "model" | "rule_fallback" | "frontend_mock";
            /** Spaceid */
            spaceId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "executed" | "expired" | "invalidated";
            /** Summary */
            summary: string;
            /** Utterance */
            utterance: string;
            /** Version */
            version: number;
        };
        /**
         * PlanGeneration
         * @description How the plan was produced. Shown in the app so sources are never confused.
         */
        PlanGeneration: {
            /**
             * Fallbackreason
             * @description Why the rule engine was used instead of the model
             */
            fallbackReason: string | null;
            /**
             * Goal
             * @description Experience goal stated by the model
             */
            goal: string | null;
            /**
             * Latencyms
             * @description Time from request to plan (server side)
             */
            latencyMs: number;
            /**
             * Moderequested
             * @enum {string}
             */
            modeRequested: "rule" | "model";
            /**
             * Model
             * @description Model name actually called; null for rule plans
             */
            model: string | null;
            /**
             * Provider
             * @description e.g. deepseek; null for rule plans
             */
            provider: string | null;
        };
        /** PlannerInfo */
        PlannerInfo: {
            /**
             * Defaultmode
             * @enum {string}
             */
            defaultMode: "rule" | "model";
            /** Model */
            model: string | null;
            /**
             * Modelconfigured
             * @description A provider and key are configured server-side (not proof it works)
             */
            modelConfigured: boolean;
            /** Provider */
            provider: string | null;
            /** Timeoutms */
            timeoutMs: number;
        };
        /**
         * RequestContext
         * @description Who is acting, for whom, and where. Checked server-side against demo memberships.
         */
        RequestContext: {
            /** Accountid */
            accountId: string;
            /** Personid */
            personId: string;
            /** Spaceid */
            spaceId: string;
        };
        /** RestPreference */
        RestPreference: {
            /**
             * Actargettempc
             * @description Preferred AC set point, Celsius
             */
            acTargetTempC: number;
            /**
             * Curtainopenpercent
             * @description Preferred curtain opening, percent
             */
            curtainOpenPercent: number;
            /**
             * Lightbrightness
             * @description Preferred light brightness, percent
             */
            lightBrightness: number;
        };
        /**
         * Scene
         * @description Proactive-service scene shown in the app. Status must match the real implementation.
         */
        Scene: {
            /** Description */
            description: string;
            /** Sceneid */
            sceneId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "implemented" | "planned";
            /** Title */
            title: string;
            /** Trigger */
            trigger: string;
            /**
             * Verification
             * @description How the status was verified, shown to users
             */
            verification: string;
        };
        /** ScenesResponse */
        ScenesResponse: {
            /** Items */
            items: components["schemas"]["Scene"][];
        };
        /** Service */
        Service: {
            /**
             * Adjustments
             * @description Automatic adjustments made by events so far
             */
            adjustments: number;
            /** Lastadjustedat */
            lastAdjustedAt: string | null;
            /** Personid */
            personId: string;
            /** Planid */
            planId: string;
            /** Planversion */
            planVersion: number;
            /**
             * Plannermode
             * @description Mode used for this service's plans; event re-planning follows it
             * @enum {string}
             */
            plannerMode: "rule" | "model";
            /** Serviceid */
            serviceId: string;
            /** Spaceid */
            spaceId: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "stopped";
            /** Stoppedat */
            stoppedAt: string | null;
        };
        /** Space */
        Space: {
            defaultRestPreference: components["schemas"]["RestPreference"];
            /** Name */
            name: string;
            /** Spaceid */
            spaceId: string;
        };
        /** StopServiceRequest */
        StopServiceRequest: {
            context: components["schemas"]["RequestContext"];
        };
        /** StopServiceResponse */
        StopServiceResponse: {
            deviceState: components["schemas"]["DeviceState"];
            service: components["schemas"]["Service"];
        };
        /**
         * UnlockPersonRequest
         * @description Demo PIN check before switching person on a shared tablet. NOT authentication.
         */
        UnlockPersonRequest: {
            /** Accountid */
            accountId: string;
            /** Pin */
            pin?: string | null;
        };
        /** UnlockPersonResponse */
        UnlockPersonResponse: {
            /** Note */
            note: string;
            /** Personid */
            personId: string;
            /** Unlocked */
            unlocked: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBootstrap: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resetDemo: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unlockPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnlockPersonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlockPersonResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRestPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmPlanResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getScenes: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stopService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopServiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopServiceResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query: {
                accountId: string;
                limit?: number;
            };
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDeviceState: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceState"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    injectEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResult"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
