/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assistant/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Main Agent entry: routes the message and returns a plan (to confirm) or a short answer.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bootstrap */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["resetDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/undo/{undo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo Device Control
         * @description Restore the exact value the device held before the write, while the window is open.
         */
        post: operations["undoDeviceControl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory
         * @description Only the acting person's own preference plus shared space rules.
         */
        get: operations["getMemory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/preference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Preference */
        put: operations["updatePreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock Person
         * @description Demo PIN check before switching person. Not authentication.
         */
        post: operations["unlockPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/rest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rest Plan */
        post: operations["createRestPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Plan */
        post: operations["confirmPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenes */
        get: operations["getScenes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{service_id}/clock/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Clock
         * @description Simulated night clock (demo only). minutes=null jumps to the next pending step; each step runs once.
         */
        post: operations["advanceClock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{service_id}/sleep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Sleep
         * @description Explicit simulated sleep signal for the pitch demo; not a real sensor integration.
         */
        post: operations["simulateSleep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{service_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Service */
        post: operations["stopService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device State */
        get: operations["getDeviceState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/devices/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Control Device
         * @description Direct control from the device panel: executes at once, then offers an undo window.
         */
        post: operations["controlDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/energy-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Energy Mode */
        put: operations["setEnergyMode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/energy/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Offline Energy Simulation
         * @description Supplied fixed-day MATD3 evidence. Read-only and never used as a device controller.
         */
        get: operations["getOfflineEnergySimulation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Event
         * @description Simulated environment event. There is no real sensor; results are labelled source=simulated.
         */
        post: operations["injectEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recovery Status */
        get: operations["getRecoveryStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionResult */
        ActionResult: {
            /** Actionid */
            actionId: string;
            /**
             * Command
             * @enum {string}
             */
            command: "set_brightness" | "set_target_temperature" | "set_open_percent";
            /**
             * Device
             * @enum {string}
             */
            device: "light" | "ac" | "curtain";
            /**
             * Observedvalue
             * @description Value read back from the device after the write
             */
            observedValue: number | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "succeeded" | "rejected" | "failed" | "skipped";
            /** Reason */
            reason: string | null;
            /** Value */
            value: number;
        };
        /** ActivityRecord */
        ActivityRecord: {
            action: components["schemas"]["ActionResult"] | null;
            /** Activityid */
            activityId: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "plan_created" | "plan_fallback" | "event_received" | "event_ignored" | "service_adjusted" | "plan_confirmed" | "plan_confirm_repeated" | "plan_rejected" | "action_executed" | "action_rejected" | "service_stopped" | "memory_updated" | "energy_mode_changed" | "demo_reset" | "clock_advanced" | "schedule_step_executed" | "schedule_cancelled" | "service_completed" | "service_failed" | "clarification_requested" | "clarification_resolved" | "clarification_cancelled" | "device_controlled" | "device_control_undone";
            /** Message */
            message: string;
            /** Personid */
            personId: string | null;
            /** Planid */
            planId: string | null;
            /** Serviceid */
            serviceId: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "user" | "rule_engine" | "experience_agent" | "executor" | "virtual_device" | "system" | "simulated_event" | "simulated_clock" | "frontend_mock";
            /** Spaceid */
            spaceId: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ActivityResponse */
        ActivityResponse: {
            /** Items */
            items: components["schemas"]["ActivityRecord"][];
        };
        /**
         * AdvanceClockRequest
         * @description Move the simulated night clock. minutes=null jumps to the next pending step.
         */
        AdvanceClockRequest: {
            context: components["schemas"]["RequestContext"];
            /** Minutes */
            minutes?: number | null;
        };
        /** AdvanceClockResponse */
        AdvanceClockResponse: {
            deviceState: components["schemas"]["DeviceState"];
            /**
             * Executed
             * @description Steps that came due and ran during this advance
             */
            executed: components["schemas"]["ScheduledStep"][];
            /**
             * Note
             * @description Why nothing happened, if nothing did
             */
            note: string | null;
            /** Results */
            results: components["schemas"]["ActionResult"][];
            service: components["schemas"]["Service"];
        };
        /**
         * AgentStep
         * @description One step of the 1+2 agent collaboration, kept with the plan as call evidence.
         */
        AgentStep: {
            /**
             * Agent
             * @enum {string}
             */
            agent: "orchestrator" | "memory" | "experience" | "energy" | "space_execution" | "harness";
            /** Detail */
            detail: string;
            /** Latencyms */
            latencyMs: number;
            /** Ok */
            ok: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "rule" | "model" | "rule_fallback" | "frontend_mock";
            /** Title */
            title: string;
        };
        /** AssistantMessageRequest */
        AssistantMessageRequest: {
            context: components["schemas"]["RequestContext"];
            /**
             * Conversationid
             * @description Stable id for resuming a pending clarification; scoped again by account/person/space
             */
            conversationId?: string | null;
            /** Mode */
            mode?: ("rule" | "model") | null;
            /** Text */
            text: string;
            /** Waketime */
            wakeTime?: ("06:30" | "07:00" | "07:30") | null;
        };
        /** AssistantReply */
        AssistantReply: {
            clarification?: components["schemas"]["PendingClarification"] | null;
            /** Conversationid */
            conversationId?: string | null;
            /**
             * Intent
             * @enum {string}
             */
            intent: "rest" | "device_command" | "status" | "other" | "clarification";
            /**
             * Kind
             * @enum {string}
             */
            kind: "plan" | "answer" | "clarification";
            plan: components["schemas"]["Plan"] | null;
            /** Text */
            text: string;
            /** Trace */
            trace: components["schemas"]["AgentStep"][];
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            account: components["schemas"]["DemoAccount"];
            activeService: components["schemas"]["Service"] | null;
            /** Defaultspaceid */
            defaultSpaceId: string;
            deviceState: components["schemas"]["DeviceState"];
            /**
             * Mode
             * @constant
             */
            mode: "demo";
            /** Persons */
            persons: components["schemas"]["Person"][];
            planner: components["schemas"]["PlannerInfo"];
            /** Spaces */
            spaces: components["schemas"]["Space"][];
        };
        /** ConfirmPlanRequest */
        ConfirmPlanRequest: {
            context: components["schemas"]["RequestContext"];
            /** Planversion */
            planVersion: number;
        };
        /** ConfirmPlanResponse */
        ConfirmPlanResponse: {
            deviceState: components["schemas"]["DeviceState"];
            plan: components["schemas"]["Plan"];
            /**
             * Repeated
             * @description True when the plan was already executed; nothing was re-run
             */
            repeated: boolean;
            /** Results */
            results: components["schemas"]["ActionResult"][];
            /** @description Null for direct device commands (no rest service) */
            service: components["schemas"]["Service"] | null;
        };
        /** CreateRestPlanRequest */
        CreateRestPlanRequest: {
            context: components["schemas"]["RequestContext"];
            /**
             * Mode
             * @description null = server default
             */
            mode?: ("rule" | "model") | null;
            /** Utterance */
            utterance: string;
            /** Waketime */
            wakeTime?: ("06:30" | "07:00" | "07:30") | null;
        };
        /**
         * DemoAccount
         * @description Demo identity only. This is NOT authentication.
         */
        DemoAccount: {
            /** Accountid */
            accountId: string;
            /** Displayname */
            displayName: string;
            /** Isdemo */
            isDemo: boolean;
        };
        /** DeviceAction */
        DeviceAction: {
            /** Actionid */
            actionId: string;
            /**
             * Command
             * @enum {string}
             */
            command: "set_brightness" | "set_target_temperature" | "set_open_percent";
            /**
             * Device
             * @enum {string}
             */
            device: "light" | "ac" | "curtain";
            /**
             * Label
             * @description Human readable description shown in the app
             */
            label: string;
            /** Value */
            value: number;
        };
        /**
         * DeviceControlRequest
         * @description Direct control from the device panel. Still goes through the Harness executor.
         */
        DeviceControlRequest: {
            context: components["schemas"]["RequestContext"];
            /**
             * Device
             * @enum {string}
             */
            device: "light" | "ac" | "curtain";
            /** Value */
            value: number;
        };
        /** DeviceControlResponse */
        DeviceControlResponse: {
            deviceState: components["schemas"]["DeviceState"];
            result: components["schemas"]["ActionResult"];
            /** @description Null when the write did not succeed */
            undo: components["schemas"]["UndoWindow"] | null;
        };
        /** DeviceState */
        DeviceState: {
            /** Actargettempc */
            acTargetTempC: number;
            /** Curtainopenpercent */
            curtainOpenPercent: number;
            /** Lightbrightness */
            lightBrightness: number;
            /**
             * Source
             * @enum {string}
             */
            source: "virtual_device" | "frontend_mock";
            /** Spaceid */
            spaceId: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /**
             * Version
             * @description Increments on every successful device write
             */
            version: number;
        };
        /**
         * EnergyAdvice
         * @description Rule-based energy advice. Loads are rough rule estimates, not measurements.
         */
        EnergyAdvice: {
            /**
             * Applied
             * @description True only in eco mode when the recommendation changed the set point
             */
            applied: boolean;
            /** Comfortmaxc */
            comfortMaxC: number;
            /** Comfortminc */
            comfortMinC: number;
            /** Loadkwafter */
            loadKwAfter: number;
            /** Loadkwbefore */
            loadKwBefore: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "comfort_first" | "eco";
            /** Outdoortempc */
            outdoorTempC: number;
            /** Reason */
            reason: string;
            /** Recommendedacc */
            recommendedAcC: number;
            /** Requestedacc */
            requestedAcC: number;
            /**
             * Source
             * @enum {string}
             */
            source: "rule" | "frontend_mock";
            /**
             * Tariff
             * @enum {string}
             */
            tariff: "peak" | "offpeak";
            /**
             * Tierafter
             * @enum {string}
             */
            tierAfter: "low" | "medium" | "high";
            /**
             * Tierbefore
             * @enum {string}
             */
            tierBefore: "low" | "medium" | "high";
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "NOT_EDITABLE" | "VALIDATION_ERROR" | "NOT_FOUND" | "FORBIDDEN_CONTEXT" | "PLAN_EXPIRED" | "PLAN_INVALIDATED" | "PLAN_VERSION_MISMATCH" | "SERVICE_ALREADY_ACTIVE" | "SERVICE_NOT_ACTIVE" | "SPACE_BUSY" | "PIN_INVALID" | "UNDO_EXPIRED" | "UNDO_INVALIDATED" | "INTERNAL_ERROR";
            /** Details */
            details: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EventResult */
        EventResult: {
            deviceState: components["schemas"]["DeviceState"];
            /** Eventid */
            eventId: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "adjusted" | "ignored";
            /** @description The adjustment plan that was executed */
            plan: components["schemas"]["Plan"] | null;
            /**
             * Reason
             * @description Why the event was ignored, if it was
             */
            reason: string | null;
            /** Results */
            results: components["schemas"]["ActionResult"][];
            service: components["schemas"]["Service"] | null;
            /**
             * Source
             * @constant
             */
            source: "simulated";
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InjectEventRequest
         * @description Simulated environment event (demo only; there is no real sensor).
         */
        InjectEventRequest: {
            context: components["schemas"]["RequestContext"];
            /** Roomtempc */
            roomTempC: number;
            /**
             * Type
             * @constant
             */
            type: "room_temperature_changed";
        };
        /**
         * MemoryView
         * @description What the requesting person may see: only their own preference plus shared space rules.
         */
        MemoryView: {
            /** Editable */
            editable: boolean;
            /** Isguest */
            isGuest: boolean;
            /** Personid */
            personId: string;
            preference: components["schemas"]["RestPreference"];
            /** Sharedrules */
            sharedRules: components["schemas"]["SpaceRule"][];
            /** Updatedat */
            updatedAt: string | null;
        };
        /**
         * OfflineEnergyAsset
         * @description A read-only asset represented by the offline energy simulation.
         */
        OfflineEnergyAsset: {
            /**
             * Control
             * @description Explains whether this is an App control or offline simulation context
             */
            control: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "supply" | "demand" | "storage" | "trading" | "backup";
        };
        /**
         * OfflineEnergyMetric
         * @description A supplied one-day benchmark metric. It is not a real-time App measurement.
         */
        OfflineEnergyMetric: {
            /**
             * Key
             * @enum {string}
             */
            key: "daily_cost" | "grid_import" | "peak_import" | "comfort_violation";
            /** Label */
            label: string;
            /** Lowerisbetter */
            lowerIsBetter: boolean;
            /** Matd3 */
            matd3: number;
            /** Rule */
            rule: number;
            /** Unit */
            unit: string;
        };
        /** OfflineEnergyProfilePoint */
        OfflineEnergyProfilePoint: {
            /** Baseloadkw */
            baseLoadKw: number;
            /** Buypriceusdperkwh */
            buyPriceUsdPerKwh: number;
            /** Hour */
            hour: number;
            /** Outdoortempf */
            outdoorTempF: number;
            /** Pvkw */
            pvKw: number;
            /** Windkw */
            windKw: number;
        };
        /**
         * OfflineEnergySimulation
         * @description Supplied fixed-day offline evidence; deliberately separate from online energy rules.
         */
        OfflineEnergySimulation: {
            /** Agentcount */
            agentCount: number;
            /** Assets */
            assets: components["schemas"]["OfflineEnergyAsset"][];
            /** Controller */
            controller: string;
            /** Limits */
            limits: string[];
            /** Metrics */
            metrics: components["schemas"]["OfflineEnergyMetric"][];
            /** Profile */
            profile: components["schemas"]["OfflineEnergyProfilePoint"][];
            /** Resolution */
            resolution: string;
            /** Scenario */
            scenario: string;
            /**
             * Source
             * @constant
             */
            source: "provided_precomputed_offline_simulation";
        };
        /**
         * PendingClarification
         * @description A resumable question in one person/space conversation.
         */
        PendingClarification: {
            /** Accountid */
            accountId: string;
            /** Clarificationid */
            clarificationId: string;
            /** Conversationid */
            conversationId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Originaltext */
            originalText: string;
            /** Personid */
            personId: string;
            /** Question */
            question: string;
            /** Spaceid */
            spaceId: string;
            /**
             * Targetintent
             * @enum {string}
             */
            targetIntent: "rest" | "device_command";
        };
        /** Person */
        Person: {
            /**
             * Avatarcolor
             * @description Display color for the avatar
             */
            avatarColor: string;
            /** Description */
            description: string;
            /**
             * Haspin
             * @description A demo PIN guards switching to this person (the PIN itself is never sent)
             */
            hasPin: boolean;
            /**
             * Isguest
             * @description Guest / shared-space context: space defaults, no personal profile
             */
            isGuest: boolean;
            /** Name */
            name: string;
            /** Personid */
            personId: string;
            /** @description Omitted in shared listings; read your own via the memory endpoint */
            restPreference?: components["schemas"]["RestPreference"] | null;
        };
        /** Plan */
        Plan: {
            /** Actions */
            actions: components["schemas"]["DeviceAction"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            energy?: components["schemas"]["EnergyAdvice"] | null;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            generation: components["schemas"]["PlanGeneration"];
            /** Notes */
            notes: string[];
            /** Personid */
            personId: string;
            /** Planid */
            planId: string;
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "rest" | "rest_adjustment" | "device_command";
            /**
             * Schedule
             * @description Overnight schedule confirmed together with a rest plan; empty otherwise
             */
            schedule: components["schemas"]["ScheduledStep"][];
            /**
             * Source
             * @enum {string}
             */
            source: "rule" | "model" | "rule_fallback" | "frontend_mock";
            /** Spaceid */
            spaceId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "executed" | "expired" | "invalidated";
            /** Summary */
            summary: string;
            /** Trace */
            trace?: components["schemas"]["AgentStep"][];
            /** Utterance */
            utterance: string;
            /** Version */
            version: number;
            /**
             * Waketime
             * @description Requested simulated wake time; ignored by direct device commands
             */
            wakeTime?: ("06:30" | "07:00" | "07:30") | null;
        };
        /**
         * PlanGeneration
         * @description How the plan was produced. Shown in the app so sources are never confused.
         */
        PlanGeneration: {
            /**
             * Fallbackreason
             * @description Why the rule engine was used instead of the model
             */
            fallbackReason: string | null;
            /**
             * Goal
             * @description Experience goal stated by the model
             */
            goal: string | null;
            /**
             * Latencyms
             * @description Time from request to plan (server side)
             */
            latencyMs: number;
            /**
             * Moderequested
             * @enum {string}
             */
            modeRequested: "rule" | "model";
            /**
             * Model
             * @description Model name actually called; null for rule plans
             */
            model: string | null;
            /**
             * Provider
             * @description e.g. deepseek; null for rule plans
             */
            provider: string | null;
        };
        /** PlannerInfo */
        PlannerInfo: {
            /**
             * Defaultmode
             * @enum {string}
             */
            defaultMode: "rule" | "model";
            /** Model */
            model: string | null;
            /**
             * Modelconfigured
             * @description A provider and key are configured server-side (not proof it works)
             */
            modelConfigured: boolean;
            /** Provider */
            provider: string | null;
            /** Timeoutms */
            timeoutMs: number;
        };
        /**
         * RecoveryStatus
         * @description Result of the startup reconciliation; observable evidence, not a claim of exact device recovery.
         */
        RecoveryStatus: {
            /** Activeservices */
            activeServices: number;
            /** Cancelledunknownsteps */
            cancelledUnknownSteps: number;
            /**
             * Checkedat
             * Format: date-time
             */
            checkedAt: string;
            /** Clearedinflightflags */
            clearedInflightFlags: number;
            /** Devicestatereconciled */
            deviceStateReconciled: boolean;
            /** Note */
            note: string;
            /**
             * Store
             * @enum {string}
             */
            store: "memory" | "postgresql";
        };
        /**
         * RequestContext
         * @description Who is acting, for whom, and where. Checked server-side against demo memberships.
         */
        RequestContext: {
            /** Accountid */
            accountId: string;
            /** Personid */
            personId: string;
            /** Spaceid */
            spaceId: string;
        };
        /** RestPreference */
        RestPreference: {
            /**
             * Actargettempc
             * @description Preferred AC set point, Celsius
             */
            acTargetTempC: number;
            /**
             * Curtainopenpercent
             * @description Preferred curtain opening, percent
             */
            curtainOpenPercent: number;
            /**
             * Lightbrightness
             * @description Preferred light brightness, percent
             */
            lightBrightness: number;
        };
        /**
         * Scene
         * @description Proactive-service scene shown in the app. Status must match the real implementation.
         */
        Scene: {
            /** Description */
            description: string;
            /** Sceneid */
            sceneId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "implemented" | "planned";
            /** Title */
            title: string;
            /** Trigger */
            trigger: string;
            /**
             * Verification
             * @description How the status was verified, shown to users
             */
            verification: string;
        };
        /** ScenesResponse */
        ScenesResponse: {
            /** Items */
            items: components["schemas"]["Scene"][];
        };
        /**
         * ScheduledStep
         * @description One timed step of the overnight schedule. Driven by a simulated clock, never by wall time.
         */
        ScheduledStep: {
            /** Actions */
            actions: components["schemas"]["DeviceAction"][];
            /**
             * At
             * @description Simulated local time, HH:MM
             */
            at: string;
            /** Executedat */
            executedAt: string | null;
            /**
             * Offsetmin
             * @description Minutes after the simulated night start
             */
            offsetMin: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "sleep" | "deep" | "wake";
            /**
             * Source
             * @enum {string}
             */
            source: "rule" | "frontend_mock";
            /**
             * Status
             * @description running = claimed by one clock advance; a step runs at most once
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "cancelled";
            /** Stepid */
            stepId: string;
            /** Title */
            title: string;
        };
        /** Service */
        Service: {
            /**
             * Adjustments
             * @description Automatic adjustments made by events so far
             */
            adjustments: number;
            /** Lastadjustedat */
            lastAdjustedAt: string | null;
            /**
             * Nightclock
             * @description Simulated local time of the overnight schedule, HH:MM
             */
            nightClock: string;
            /**
             * Nightoffsetmin
             * @description Simulated minutes since the night start
             */
            nightOffsetMin: number;
            /** Personid */
            personId: string;
            /** Planid */
            planId: string;
            /** Planversion */
            planVersion: number;
            /**
             * Plannermode
             * @description Mode used for this service's plans; event re-planning follows it
             * @enum {string}
             */
            plannerMode: "rule" | "model";
            /** Schedule */
            schedule: components["schemas"]["ScheduledStep"][];
            /** Serviceid */
            serviceId: string;
            /**
             * Sleepdetectedat
             * @description Set only when the demo's explicit simulated-sleep event was used
             */
            sleepDetectedAt?: string | null;
            /** Spaceid */
            spaceId: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "stopped" | "completed" | "failed";
            /** Stoppedat */
            stoppedAt: string | null;
            /**
             * Waketime
             * @description Requested simulated wake time for this service
             * @default 07:00
             * @enum {string}
             */
            wakeTime: "06:30" | "07:00" | "07:30";
        };
        /** SetEnergyModeRequest */
        SetEnergyModeRequest: {
            context: components["schemas"]["RequestContext"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "comfort_first" | "eco";
        };
        /**
         * SimulateSleepRequest
         * @description Explicit demo sleep signal; this is not a physical sensor integration.
         */
        SimulateSleepRequest: {
            context: components["schemas"]["RequestContext"];
        };
        /** Space */
        Space: {
            defaultRestPreference: components["schemas"]["RestPreference"];
            /**
             * Energymode
             * @description comfort_first: advise only; eco: apply advice inside the comfort band
             * @enum {string}
             */
            energyMode: "comfort_first" | "eco";
            /** Name */
            name: string;
            /** Spaceid */
            spaceId: string;
        };
        /**
         * SpaceRule
         * @description Shared rule of a space. Visible to everyone in the space (unlike personal preferences).
         */
        SpaceRule: {
            /**
             * Enforced
             * @description True when code enforces it (not just displayed)
             */
            enforced: boolean;
            /** Ruleid */
            ruleId: string;
            /** Text */
            text: string;
        };
        /** StopServiceRequest */
        StopServiceRequest: {
            context: components["schemas"]["RequestContext"];
        };
        /** StopServiceResponse */
        StopServiceResponse: {
            deviceState: components["schemas"]["DeviceState"];
            service: components["schemas"]["Service"];
        };
        /** UndoRequest */
        UndoRequest: {
            context: components["schemas"]["RequestContext"];
        };
        /** UndoResponse */
        UndoResponse: {
            deviceState: components["schemas"]["DeviceState"];
            /** Restoredvalue */
            restoredValue: number;
            result: components["schemas"]["ActionResult"];
        };
        /**
         * UndoWindow
         * @description A short chance to put a device back exactly where it was.
         *
         *     Low-risk device writes execute immediately and offer this instead of a confirmation
         *     dialog: on a control people touch dozens of times a day, a dialog trains them to
         *     dismiss it without reading. The window lives in the running process only — after a
         *     restart there is nothing to undo, which is the intended semantic, not an omission.
         */
        UndoWindow: {
            /** Appliedvalue */
            appliedValue: number;
            /**
             * Device
             * @enum {string}
             */
            device: "light" | "ac" | "curtain";
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Label */
            label: string;
            /**
             * Previousvalue
             * @description Exact value read back before the write; undo restores this
             */
            previousValue: number;
            /** Spaceid */
            spaceId: string;
            /** Undoid */
            undoId: string;
        };
        /**
         * UnlockPersonRequest
         * @description Demo PIN check before switching person on a shared tablet. NOT authentication.
         */
        UnlockPersonRequest: {
            /** Accountid */
            accountId: string;
            /** Pin */
            pin?: string | null;
        };
        /** UnlockPersonResponse */
        UnlockPersonResponse: {
            /** Note */
            note: string;
            /** Personid */
            personId: string;
            /** Unlocked */
            unlocked: boolean;
        };
        /** UpdatePreferenceRequest */
        UpdatePreferenceRequest: {
            context: components["schemas"]["RequestContext"];
            preference: components["schemas"]["RestPreference"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantReply"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBootstrap: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resetDemo: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    undoDeviceControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                undo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UndoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMemory: {
        parameters: {
            query: {
                accountId: string;
                personId: string;
                spaceId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updatePreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unlockPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnlockPersonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlockPersonResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRestPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmPlanResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getScenes: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    advanceClock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceClockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceClockResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulateSleep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateSleepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceClockResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stopService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopServiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopServiceResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query: {
                accountId: string;
                limit?: number;
            };
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDeviceState: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceState"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    controlDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceControlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceControlResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setEnergyMode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEnergyModeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Space"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOfflineEnergySimulation: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfflineEnergySimulation"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    injectEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResult"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecoveryStatus: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryStatus"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
